services:
  - type: web
    name: admin-caller-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: COOLDOWN_SECONDS
        value: "30
